apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
  - name: main
    image: openjdk:8
    command: ["sleep", "9999999"]
  - name: ambassador
    image: yu3papa/kubectl-proxy:1.0
