apiVersion: v1
kind: Pod
metadata:
  name: guestbook-manual
  namespace: custom-namespace
spec:
  containers:
  - image: yu3papa/k8s_guestbook:1.0
    name: guestbook
    ports:
    - containerPort: 8080
      protocol: TCP