apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      name: guestbook
      labels:
        app: guestbook
    spec:
      containers:
      - image: yu3papa/k8s_guestbook:v1
        name: springboot
