apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guestbook-pvc 
spec:
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      disk: ssd
  accessModes:
    - ReadWriteOnce
  storageClassName: ""