apiVersion: v1
kind: PersistentVolume
metadata:
  name: guestbook-pv
  labels:
    disk: ssd
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-share/guestbook-pv
    server: 192.168.137.100

