apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kubernetes-simple-app
  targetCPUUtilizationPercentage: 30
  
  