apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: yu3papa/k8s_calculator:ingress
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calculator
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: calculator