apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: guestbook
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
         - guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: yu3papa/k8s_guestbook:1.0
