# Headless Service used by guestbook
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  ports:
  - port: 13306
    name: mysql
    targetPort: 3306
    protocol: TCP
  clusterIP: None
  selector:
    name: mysql
    
---
# 외부사용자 접속용
# Delete this if not required
apiVersion: v1
kind: Service
metadata:
  name: mysql-client
  labels:
    name: mysql
spec:
  type: NodePort
  ports:
  - port: 13306
    name: server
    targetPort: 3306
    nodePort: 30306
    protocol: TCP
  selector:
    name: mysql
