apiVersion: v1
kind: Pod
metadata:
  name: guestbook-pod-env-cm-secret
spec:
  containers:
  - image: yu3papa/k8s_guestbook:env-secret
    name: guestbook
    envFrom:
    - configMapRef:
        name: guestbook-config
    env:
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: guestbook-secret
          key: MYSQL_USER
    - name: MYSQL_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: guestbook-secret
          key: MYSQL_USER_PASSWORD
    ports:
    - containerPort: 8080
      protocol: TCP