apiVersion: v1
kind: Pod
metadata:
  name: guestbook-pod-env-cm-secret-all
spec:
  containers:
  - image: yu3papa/k8s_guestbook:env-secret
    name: guestbook
    envFrom:
    - configMapRef:
        name: guestbook-config
    - secretRef:
        name: guestbook-secret
    ports:
    - containerPort: 8080
      protocol: TCP