apiVersion: v1
kind: Pod
metadata:
  name: cowsay-env-from-configmap-allentry
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    envFrom:
    - configMapRef: 
        name: cowsay-config
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}