apiVersion: v1
kind: Pod
metadata:
  name: guestbook-nfs
spec:
  volumes:
  - name: guestbook-data
    nfs:
      server: 192.168.137.100
      path: /nfs-share/guestbook-data
  containers:
  - image: yu3papa/k8s_guestbook:1.0
    name: guestbook
    volumeMounts:
    - name: guestbook-data
      mountPath: /app/upload
    ports:
    - containerPort: 8080
      protocol: TCP