apiVersion: v1
kind: Pod
metadata:
  name: guestbook-pod-use-xtradb
spec:
  containers:
  - image: yu3papa/k8s_guestbook:env-secret
    name: guestbook
    envFrom:
    - configMapRef:
        name: guestbook-xtradb-config
    ports:
    - containerPort: 8080
      protocol: TCP
